id: P005595
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG14713
  title: ཀྲུང་ཧྭ་སྔོ་འབུམ།  བོད་ལུགས་སྨན་རྫས། ༼བོད་ཡིག་པར་མ།༽
  author: ''
  volumes:
    38a70c7f5af1411baa07068281c941b0:
      image_group_id: I2PD18128
      title: ''
      volume_number: 1
      total_pages: 940
      base_file: v001.txt
